### ISSUE TITLE
Would like to use interact('.tap-target') . onTab

### ISSUE THREAD

**Issue by mcginkel** [eriklieben/aurelia-interactjs#9]
**I'm submitting a feature request**
I would like to use interact('.tap-target') .onTab en onHold. I can add it to the code with a pull request, but would like some guidelines on the implementation.

- What attributes would you add to support this?
- would it be part of dragable or resizable or dropzone or something new ?

* **What is the expected behavior?**
Happy use of tab, doubletab and hold

* **What is the motivation / use case for changing the behavior?**
I want to start an editor when i hold or tab on a draggable/resizable element.

Thanks for making this library available.

**Comment by eriklieben** [comment]
Hi Kees, this is the issue we talked about at the Aurelia Amsterdam meet up right?
Feel free to send in a pull request if you already have the code, then I look at it, merge and release it so others can enjoy this functionality also.

To answer your questions: 

I've glanced at the interact.js documentation for the pointer events (http://interactjs.io/docs/#pointer-events). It looks like it would work on any interactjs wrapped element, so draggable, dropzone, resizable & gesturable. If we do that then I guess the only issue is that it might fire a tab event multiple times, for example: if something is draggable and resizable. Need to try that out to see how it behaves.

Because of that, I would probably just add it to the draggable and dropzone, because that would most likely be the elements users would want to listen on for these events I guess.

If I needed to implement it, I would have probably let it delegate/ dispatch the events to attributes/events that look like this:
interact-pointer-down
interact-pointer-move
interact-pointer-up
interact-pointer-cancel
interact-pointer-tap
interact-pointer-doubletap
interact-pointer-hold

But that's just my guess :-) Feel free to deviate from that.

Thanks,

Erik
